# Generated by Django 4.1 on 2022-09-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_list_2',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
