# Generated by Django 4.1 on 2022-09-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_customer_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_list_2',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_list',
            field=models.BinaryField(),
        ),
    ]
