# Generated by Django 4.1 on 2022-09-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_remove_order_product_list_2_alter_order_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ucoins', 'Ucoins'), ('rubles', 'Rubles')], default='ucoins', max_length=6),
        ),
    ]
