# Generated by Django 4.1 on 2022-09-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='office',
            field=models.CharField(choices=[('Mira', 'Mira'), ('Lenina', 'Lenina'), ('Yasnaya', 'Yasnaya')], default='Lenina', max_length=7),
        ),
    ]
