# Generated by Django 4.1.1 on 2022-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_order_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Formed', 'Formed'), ('Completed', 'Completed')], default='Accepted', max_length=9),
        ),
    ]
