# Generated by Django 4.1.1 on 2022-10-05 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_api', '0007_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='patronymic',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='BalanceReplenish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.PositiveSmallIntegerField(help_text='ID пользователя, который начисли баланс.')),
                ('count', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, default='', max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пополнение баланса',
                'verbose_name_plural': 'История ополнений балансов',
            },
        ),
    ]
