# Generated by Django 4.1.1 on 2022-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_alter_customer_first_name_alter_customer_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
