# Generated by Django 4.1.1 on 2022-10-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_secretword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecretWord',
        ),
    ]
