# Generated by Django 4.1.1 on 2022-10-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0011_secretword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretword',
            options={'ordering': ['-created_date'], 'verbose_name': 'Секретное слово', 'verbose_name_plural': 'Секретные слова'},
        ),
    ]
