# Generated by Django 4.1.1 on 2022-10-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0012_alter_secretword_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancereplenish',
            name='admin_id',
            field=models.PositiveSmallIntegerField(help_text='ID пользователя, который начислил баланс.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='office',
            field=models.CharField(max_length=150),
        ),
    ]
