# Generated by Django 4.1.1 on 2022-10-21 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_api', '0014_remove_customer_role_customer_admin_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Accepted', max_length=9),
        ),
        migrations.CreateModel(
            name='BalanceWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.PositiveSmallIntegerField(help_text='ID пользователя, который начислил баланс.')),
                ('count', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, default='', max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Списание баланса',
                'verbose_name_plural': 'История списания балансов',
            },
        ),
    ]
