# Generated by Django 4.1 on 2022-09-04 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_date'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ['product_item', 'main'], 'verbose_name': 'Фото цвета товара', 'verbose_name_plural': 'Фото цветов товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productphoto',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='theme',
            field=models.CharField(choices=[('Ussc', 'Ussc'), ('Udv', 'Udv')], db_index=True, default='Ussc', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='productphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('main', True)), fields=('product_item', ), name='photo_main_constrain'),
        ),
    ]
