# Generated by Django 4.1 on 2022-09-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options_alter_productphoto_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productphoto',
            name='photo_main_constrain',
        ),
        migrations.AddConstraint(
            model_name='productphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('main', True)), fields=('product_item',), name='photo_main_constrain'),
        ),
    ]
