# Generated by Django 4.1 on 2022-09-07 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productphoto_photo_main_constrain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['-product__created_date'], 'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ['product_item', '-main'], 'verbose_name': 'Фото цвета товара', 'verbose_name_plural': 'Фото цветов товаров'},
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='color',
            new_name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='have_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productitem',
            name='state',
            field=models.CharField(choices=[('actual', 'Actual'), ('hidden', 'Hidden')], default='hidden', max_length=6),
        ),
        migrations.AddField(
            model_name='productcart',
            name='size',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.size'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='sizes',
            field=models.ManyToManyField(to='store.size'),
        ),
    ]
