# Generated by Django 4.1 on 2022-09-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_size_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size'),
        ),
    ]
