# Generated by Django 4.1 on 2022-09-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productcart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='store.size'),
        ),
    ]
